config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  resources :plants,      only: [:index, :show]
  resource  :leaderboard, only: [:show], controller: 'leaderboard'

  namespace :garden do
    root to: 'dashboard#show'

    resources :care_moments, only: [:index]

    resources :plants do
      resources :care_moments, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/care_moment.rb
class CareMoment < ApplicationRecord
  MOMENTS = {
    weed: {
      points: 2, # per month : 4
      min_frequency_in_days: 15
    },
    water: {
      points: 10, # per month : 80
      min_frequency_in_days: 3
    },
    repot: {
      points: 100, # per month : 25
      min_frequency_in_days: 300
    }
  }

  belongs_to :plant

  validates :code,   presence: true, inclusion: { in: MOMENTS.keys.map(&:to_s) }
  validates :points, presence: true, numericality: { greater_than: 0 }
end

app/models/plant.rb
class Plant < ApplicationRecord
  ROOMS = %w(entrance living-room bedroom bathroom office)
  SIZES = %w(small medium tall)

  belongs_to :user
  has_many :care_moments, dependent: :destroy

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  LEVELS = {
    # NUMBER : RANGE
    # beginner
    0 => 0...10,
    # now
    1 => 10...20,
    # one week
    2 => 20...100,
    # one month
    3 => 100...500,
    # not so quick (4-5 month)
    4 => 500...1300,
    # one year
    5 => 1300...1985,
    # one year and a half
    6 => 1985..Float::INFINITY
  }

  devise :database_authenticatable, :registerable,
         :recoverable, :validatable

  has_many :plants, dependent: :destroy
  has_many :care_moments, through: :plants

  scope :top, -> (limit) do
    select('users.*, COUNT(DISTINCT plants.id) AS plants_count, COUNT(care_moments.id) AS care_moments_count').
    joins(plants: :care_moments).
    group('users.id').
    order(level: :desc, care_points: :desc).
    limit(limit)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/garden/care_moments_controller.rb
class Garden::CareMomentsController < ApplicationController
  def index
    @care_moments = current_user.care_moments.eager_load(:plant).order(date: :desc)
  end

  def create
    @plant = current_user.plants.find(params[:plant_id])
    @code  = params[:code]

    generate_care_moment if action_can_be_performed?

    redirect_to params[:src] == 'dashboard' ? garden_root_path : garden_plant_path(@plant)
  end

  private

  def too_soon?
    last_moment  = @plant.care_moments.where(code: @code).order('date DESC').first
      
    last_moment && Date.today < last_moment.date + @moment_specs[:min_frequency_in_days].days
  end

  def generate_care_moment
    if GenerateCareMomentService.new(@plant, @code).call
      flash[:notice] = "Action successfully saved."
    else
      flash[:alert] = "Unable to save the action."
    end
  end

  def action_can_be_performed?
    if !@code
      flash[:alert] = "What action do you want to perform?"
      false
    elsif too_soon?
      flash[:alert] = "You can't #{@code} your plant right now. It's too soon."
      false
    else
      true
    end
  end
end

app/controllers/garden/dashboard_controller.rb
class Garden::DashboardController < ApplicationController
  def show
    @last_level = User::LEVELS.keys.last

    @user = UserPresenter.new(current_user)
    @latest_plants       = @user.plants.order(created_at: :desc).limit(3)
    @plants_needing_care = PlantQuery.relation(@user.plants).needing_care
    @plants_needing_care = PlantPresenter.wrap(@plants_needing_care)
  end
end

app/controllers/garden/plants_controller.rb
class Garden::PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  def index
    @plants = current_user.plants
  end

  def show
    @moments = @plant.care_moments.order(date: :desc)

    @last_moment_per_code = CareMomentQuery.relation(@plant.care_moments).
                              last_moment_per_code.
                              each_with_object({}) do |moment, moments|
                                moments[moment.code] = moment
                              end
  
    @plant = PlantPresenter.new(@plant)
  end

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.user = current_user

    if @plant.save
      flash[:notice] = 'Your plant was successfully added to your garden.'
      redirect_to garden_plant_path(@plant)
    else
      flash.now[:alert] = 'Unable to add your plant'
      render :new
    end
  end

  def edit
  end

  def update
    @plant.assign_attributes(plant_params)

    if @plant.save
      flash[:notice] = 'Your plant was successfully updated.'
      redirect_to garden_plant_path(@plant)
    else
      flash.now[:alert] = 'Unable to update your plant'
      render :edit
    end
  end

  def destroy
    @plant.destroy!
    redirect_to garden_plants_path
  end

  private

  def plant_params
    params.require(:plant).permit(
      :name,
      :age_in_months,
      :size,
      :room,
      :photo_url
    )
  end

  def set_plant
    @plant = PlantQuery.relation(current_user.plants).include_care_status.find(params[:id])
  end
end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
  def show
    @top_users = User.top(10)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    @latest_plants = Plant.includes(:user).order(created_at: :desc).limit(3)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @plants = Plant.includes(:user).order(created_at: :desc)
  end

  def show
    @plant = Plant.find(params[:id])

    @gardener_other_plants = @plant.user.plants.
                              eager_load(:user).
                              where.not(id: @plant.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/care_moment_helper.rb
module CareMomentHelper
  def care_moment_css_color(code)
    action_classes = {
      water: 'info',
      repot: 'success',
      weed:  'secondary'
    }
    action_classes[code.to_sym] || 'secondary'
  end
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
  def leaderboard_medal_for(rank)
    medals = {
      1 => '🥇',
      2 => '🥈',
      3 => '🥉'
    }
    medals[rank] || '🏅'
  end
end

app/helpers/plant_helper.rb
module PlantHelper
  def human_plant_size(size)
    sizes = {
      'small' => 'quite small',
      'medium' => 'almost tall'
    }
    sizes[size] || 'so tall'
  end
end

app/views/garden/care_moments/index.html.erb
<div class="container page-container">
  <div class="row">
    <div class="col col-lg-8">
      <%= link_to '< back to dashboard', garden_root_path %>
      <h1>History</h1>
      <p class="lead">
        Here you can find all moments you took care of your plants.
        <br>
        You already dedicated <strong><%= number_with_delimiter @care_moments.count, delimiter: " " %> moments</strong> to your plants for a total of <strong><%= number_with_delimiter current_user.care_points, delimiter: " " %> doses</strong> of care.
      </p>
      <table class="table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Plant</th>
            <th>Action</th>
            <th class="text-right">Doses of care</th>
          </tr>
        </thead>
        <tbody>
          <% @care_moments.each do |moment| %>
            <tr>
              <td><%= l(moment.date, format: :short) %></td>
              <td><%= link_to moment.plant.name, garden_plant_path(moment.plant) %></td>
              <td><%= moment.code %></td>
              <td class="text-right"><%= number_with_delimiter moment.points, delimiter: " " %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/garden/dashboard/show.html.erb
<div class="container page-container">
  <div class="row">
    <div class="col">
      <h1 class="">Garden</h1>
      <p class="lead">
        Welcome <%= 'back' if @latest_plants.any? %> to your interior garden <%= @user.nickname %>!
      </p>

      <p class="lead">
        <% if @user.care_points > 0 %>
          In total, you gave <strong><%= number_with_delimiter @user.care_points, delimiter: " " %> doses</strong> of care to your plants.
        <% end %>

        <% if @user.level > 0 %>
          <br>
          Thanks to that, you reached <strong>level <%= @user.level %></strong> out of <%= @last_level %>.
          <br>
          <strong><%= @user.points_to_next_level %> doses</strong> of care until next level.
        <% end %>

        <% if @user.care_points > 0 %>
          <br>
          <%= link_to 'See history', garden_care_moments_path %>
        <% end %>
      </p>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col col-lg-8">
      <h2>Care needed</h2>
      <% if @plants_needing_care.empty? %>
        <p>No action needed for now. Well done!</p>
      <% else %>
        <table class="table">
          <thead>
            <tr>
              <th>Plant</th>
              <th></th>
              <th>Care</th>
            </tr>
          </thead>
          <tbody>
            <% @plants_needing_care.each do |plant| %>
              <tr>
                <td height=100 width=100>
                  <%= link_to garden_plant_path(plant) do %>
                    <div class="bg-image" style="height: 100%; background-image: url('<%= plant.photo_url %>')" >
                    </div>
                  <% end %>
                </td>
                <td class="align-middle"><%= link_to plant.name, garden_plant_path(plant) %></td>
                <td class="align-middle">
                  <% plant.needed_care_moment_codes.each do |code| %>
                    <%= link_to code,
                                garden_plant_care_moments_path(plant, code: code, src: :dashboard),
                                method: :post,
                                class: "care-action btn btn-outline-#{care_moment_css_color(code)}"
                    %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
    <div class="col col-lg-4">
      <h2>Latest plants</h2>
      <% if @latest_plants.empty? %>
        <%= link_to 'New plant', new_garden_plant_path %>
      <% elsif @user.plants.count > 3 %>
        <%= link_to 'See all plants', garden_plants_path %>
      <% end %>

      <div class="row">
        <div class="col">
          <% @latest_plants.each do |plant| %>
            <%= link_to garden_plant_path(plant) do %>
              <%= render 'garden/plants/card', plant: plant %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/garden/plants/_card.html.erb
<div class="garden-plant float-left">
  <div class="image">
    <%= image_tag plant.photo_url, width: 150, height: 150 %>
  </div>
  <div class="details">
    <h2><%= truncate plant.name, length: 10 %></h2>
    <p class="room"><%= plant.room %></p>

    <p class="points">💚 <%= pluralize(plant.care_points, 'dose') %></p>
  </div>
</div>

app/views/garden/plants/_form.html.erb
<%= simple_form_for [:garden, plant] do |f| %>
  <%= f.input :name %>
  <%= f.input :age_in_months, as: :select, collection: 1..5, input_html: { class: "custom-select"} %>
  <%= f.input :size, as: :select, collection: Plant::SIZES, input_html: { class: "custom-select" } %>
  <%= f.input :room, as: :select, collection: Plant::ROOMS, input_html: { class: "custom-select" } %>
  <%= f.input :photo_url %>
  <%= f.submit class: 'btn btn-primary' %>
  <%= link_to 'Cancel', plant.new_record? ? garden_plants_path : garden_plant_path(plant), class: 'btn btn-ligth' %>
<% end %>

app/views/garden/plants/edit.html.erb
<div class="container page-container">
  <div class="row">
    <div class="col-sm col-md-4 offset-md-4">
      <h1>Edition of <%= @plant.name %></h1>
      <%= render 'form', plant: @plant %>
    </div>
  </div>
</div>

app/views/garden/plants/index.html.erb
<div class="container page-container">
  <div class="row">
    <div class="col">
      <h1 class="page-title">Plants from your interior garden</h1>
      <%= link_to 'New Plant', new_garden_plant_path, class: 'text-right' %>
      <br/>

      <% @plants.each do |plant| %>
        <%= link_to garden_plant_path(plant) do %>
          <%= render 'garden/plants/card', plant: plant %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/garden/plants/new.html.erb
<div class="container page-container">
  <div class="row">
    <div class="col-sm col-md-4 offset-md-4">
      <h1>New Plant</h1>
      <%= render 'form', plant: @plant %>
    </div>
  </div>
</div>

app/views/garden/plants/show.html.erb
<div class="container page-container">
  <div class="row">
    <div class="col">
      <%= link_to '< back to plants', garden_plants_path  %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm col-md-4">
      <div class="garden-plant">
        <div class="image">
          <%= image_tag @plant.photo_url, width: 200, height: 200 %>
        </div>
        <div class="details">
          <h1><%= @plant.name %></h1>
          <p class="room"><%= @plant.room %></p>
          <ul class="list-unstyled">
            <li><%= pluralize @plant.age_in_months, 'month' %></li>
            <li><%= @plant.size %> size</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="text-right" style="margin-top: 1em">
        <%= link_to 'public page', plant_path(@plant), class: "btn btn-sm btn-outline-info" %>
        <%= link_to 'edit', edit_garden_plant_path(@plant), class: "btn btn-sm btn-outline-primary" %>
        <%= link_to 'remove', garden_plant_path(@plant), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-outline-danger" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="care-actions text-center">
        <% if @moments.any? %>
          <p class="care-title">You gave <strong><%= number_with_delimiter @plant.care_points, delimiter: " " %> doses</strong> of care 💚</p>
        <% else %>
          <p class="care-title">You haven't taken care of your plant yet.</p>
        <% end %>
        
        <% @plant.needed_care_moment_codes.each do |code| %>
          <%= link_to code, garden_plant_care_moments_path(@plant, code: code), method: :post, class: "care-action btn btn-outline-#{care_moment_css_color(code)}" %>
        <% end %>
      </div>
      <% if @moments.any? %>
        <table class="table">
          <thead>
            <tr>
              <th>#</th>
              <th>Date</th>
              <th>Action</th>
              <th width=200>Doses of care</th>
            </tr>
          </thead>
          <tbody>
            <% @moments.each_with_index do |moment, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= l(moment.date, format: :short) %></td>
                <td>
                  <span class="care-badge badge badge-<%= care_moment_css_color(moment.code) %>"><%= moment.code %></span>
                </td>
                <td><%= moment.points %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_flashes.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">
    <%= image_tag "tree.png", width: 30, heigt: 30 %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse mr-auto d-flex flex-row-reverse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item <%= 'active' if request.path == plants_path %>">
        <%= link_to 'Plants', plants_path, class: 'nav-link' %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item <%= 'active' if request.path == garden_root_path %>">
          <%= link_to 'My Garden', garden_root_path, class: 'nav-link' %>
        </li>
        <li class="nav-item <%= 'active' if request.path == leaderboard_path %>">
          <%= link_to 'Leaderboard', leaderboard_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item <%= 'active' if request.path == new_user_session_path %>">
          <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bonsai</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag 'tree.png' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag    'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/leaderboard/show.html.erb
<div class="container page-container">
  <div class="row">
    <div class="col col-lg-6 offset-lg-3">
      <h1>Leaderboard</h1>
      <p class="lead">Discover the top 10 gardeners.</p>
      <table class="table">
        <thead>
          <th scope="col" class="text-center">Rank</th>
          <th scope="col">Gardener</th>
          <th scope="col">Plants</th>
          <th scope="col">Care Moments</th>
          <th scope="col" class="text-right">Doses of care</th>
          <th scope="col" class="text-center">Level</th>
        </thead>
        <tbody>
          <% @top_users.each_with_index do |user, index| %>
            <% rank = index + 1 %>
            <tr class="<%= 'table-warning' if (1..3).include?(rank) %>">
              <td class="text-center">
                <%= leaderboard_medal_for(rank) %>
              </td>
              <td><%= user.nickname || 'N/A' %></td>
              <td><%= user.plants_count %></td>
              <td><%= user.care_moments_count %></td>
              <td class="text-right"><%= number_with_delimiter user.care_points, delimiter: " " %></td>
              <td class="text-center"><%= user.level %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home">
  <div class="bg-image home-banner" style="background-image: url('https://nonagon.style/wp-content/uploads/2018/01/NONAGON-style-n9s-indoor-house-plant-green-garden-white-eco.jpg')">
    <div class="box">
      <h1>Bonsai!</h1>
      <p class="tagline">Take care of your plants on a daily basis.</p>
      <%= link_to "GET STARTED", (user_signed_in? ? garden_root_path : plants_path), class: 'btn btn-primary btn-lg' %>
    </div>
  </div>

  <div class="container home-incentives" id="go">
    <div class="row incentive">
      <div class="col-md">
        <div class="bg-image incentive-cover" style="background-image: url('https://redsquareflowers.com//wp-content/uploads/2014/09/Ficus-Fiddle-leaf-tree-WHITE-984x984.jpg')"></div>
      </div>
      <div class="col-md">
        <div class="incentive-details">
          <h3>List your plants</h3>
          <p>Add each plant of your home on Bonsai and we'll help you keep them healthy.</p>
        </div>
      </div>
    </div>
    <div class="row incentive">
      <div class="col-md">
        <div class="incentive-details">
          <h3>Share your progress</h3>
          <p>Keep track of your progress and share to the community how much you take care of your plants.</p>
        </div>
      </div>
      <div class="col-md">
        <div class="bg-image incentive-cover" style="background-image: url('https://cdn.shopify.com/s/files/1/0013/3529/6118/products/Pottery-Pots-Mini-Orb-L-Grey_Fiddle-leaf-fig-topiary_10.jpg?v=1537379014')"></div>
      </div>
    </div>
  </div>

  <div class="home-plants">
    <div class="container">
      <div class="row">
        <div class="col">
          <h2>Latest plants from our community</h2>
          <p>
            Find some inspiration for your future plant.
            <br>
            <%= link_to 'See all plants', plants_path %>
          </p>
        </div>
      </div>
      <div class="row">
        <% @latest_plants.each do |plant| %>
          <%= render 'plants/card', plant: plant %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/plants/_card.html.erb
<div class="plant">
  <%= link_to plant_path(plant) do %>
    <div class="bg-image plant-cover" style="background-image: url('<%= plant.photo_url %>')"></div>
  <% end %>
  <p class="plant-owner">by <%= plant.user.nickname %></p>
</div>

app/views/plants/index.html.erb
<div class="container page-container">
  <div class="row">
    <div class="col">
      <h1 class="text-center page-title">Plants from our community of interior gardeners</h1>
    </div>
  </div>
  <div class="row justify-content-center">
    <% @plants.each do |plant| %>
      <%= render 'card', plant: plant %>
    <% end %>
  </div>
</div>

app/views/plants/show.html.erb
<div class="container page-container">
  <div class="row">
    <div class="col bg-image plant-cover" style="background-image: url('<%= @plant.photo_url %>')">
    </div>
    <div class="col plant-identity">
      <h1>My name is <strong><%= @plant.name %></strong></h1>
      <span class="plant-gardener">owned by <%= @plant.user.nickname %></span>

      <div class="plant-details">
        <p>
          I'm <strong> <%= pluralize @plant.age_in_months, 'month' %></strong> old,

          I'm <strong><%= human_plant_size @plant.size %></strong>

          and you can find me in the <strong><%= @plant.room %></strong>.
        </p>
        <p>
          Oh and my gardener takes extra care of me. I already received <strong><%= number_with_delimiter @plant.care_points, delimiter: " " %> doses</strong> of care 💚
        </p>
      </div>
    </div>
  </div>

  <div class="gardener-other-plants">
    <div class="row">
      <div class="col">
        <h2 class="text-center"><%= @plant.user.nickname %>'s other plants</h2>
      </div>
    </div>
    <div class="row justify-content-center">
      <% @gardener_other_plants.each do |plant| %>
        <%= render 'card', plant: plant %>
      <% end %>
      </div>
    </div>
  </div>
</div>